### ISSUE TITLE
How can I display the tweets of two or more users in separate blocks?

### ISSUE THREAD

**Issue by acemir** [borisaguilar/Twitter#5]
I registered 2 users in the module backend.
I want to display de tweets of user 1 in one block and the tweets of the user 2 in another block at the same page view.
How could I do this?

**Comment by borisaguilar** [comment]
Currently is not implemented :P

**Comment by acemir** [comment]
All right! Thank you! I'll try to study how to implement this.

P.S.: The issue title was wrong. Sorry!
